version: '3.9'

services:
  frontend:
    image: node
    command: sh -c "yarn install && yarn start"
    working_dir: /app
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app

  backend:
    build: .
    command: python /src/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/src
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data:
